export * from "./About";
export * from "./Competitions";
export * from "./News";
export * from "./Contacts";
export * from "./Federations";
export * from "./Rating";
export * from "./Boxing";
export * from "./Ushu";
export * from "./Wrestling";
